# Generated by Django 5.1.3 on 2024-11-12 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
